apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: binary-container-build-0-1  # dot is not allowed in the name
spec:
  description: >-
    OSBS build task for building binary container image
  params:
    - name: OSBS_IMAGE
      description: The location of the OSBS builder image (FQDN pullspec)
      type: string
    - name: PIPELINE_RUN_NAME
      type: string
      description: PipelineRun name to reference current PipelineRun
    - name: USER_PARAMS
      type: string
      description: User parameters in JSON format
    - name: PLATFORM
      type: string
      description: platform on which to build container

  workspaces:
    - name: ws-build-dir
    - name: ws-context-dir
    - name: ws-registries-secret  # access with $(workspaces.ws-registries-secret.path)/token
    - name: ws-koji-secret  # access with $(workspaces.ws-koji-secret.path)/token
    - name: ws-reactor-config-map
    - name: ws-remote-host-auth

  steps:
    - name: binary-container-build
      image: $(params.OSBS_IMAGE)
      resources:
        requests:
          memory: 300Mi
          cpu: 250m
        limits:
          memory: 600Mi
          cpu: 395m
      script: >
        atomic-reactor -v task
        --user-params="$(params.USER_PARAMS)"
        --build-dir=$(workspaces.ws-build-dir.path)
        --context-dir=$(workspaces.ws-context-dir.path)
        --config-file=$(workspaces.ws-reactor-config-map.path)/config.yaml
        --namespace=$(context.taskRun.namespace)
        --pipeline-run-name="$(params.PIPELINE_RUN_NAME)"
        binary-container-build --platform="$(params.PLATFORM)"
