language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"
  - "pip install pytest-cov coveralls"
  - "pip install git+https://github.com/DBuildService/osbs-client"
# command to run tests
script: "py.test -vv tests --cov atomic_reactor"
# run in a docker container
sudo: false
notifications:
  email: false
after_success: "coveralls"
