apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: binary-container-0-1  # dot is not allowed in the name
spec:
  params:
    - name: osbs-image
      description: The location of the OSBS builder image (FQDN pullspec)
      type: string
    - name: user-params
      type: string
      description: User parameters in JSON format

  workspaces:
    - name: ws-container
    - name: ws-registries-secret
    - name: ws-koji-secret
    - name: ws-reactor-config-map
    - name: ws-remote-host-auth

  results:
    - name: repositories
      value: $(tasks.binary-container-set-results.results.repositories)
    - name: koji-build-id
      value: $(tasks.binary-container-set-results.results.koji-build-id)
    - name: remote_sources
      value: $(tasks.binary-container-set-results.results.remote_sources)
    - name: task_build_result_x86_64
      value: $(tasks.binary-container-build-x86-64.results.task_result)
    - name: task_build_result_s390x
      value: $(tasks.binary-container-build-s390x.results.task_result)
    - name: task_build_result_ppc64le
      value: $(tasks.binary-container-build-ppc64le.results.task_result)
    - name: task_build_result_aarch64
      value: $(tasks.binary-container-build-aarch64.results.task_result)

  tasks:
    - name: clone
      taskRef:
        name: clone-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          subPath: home-dir
          workspace: ws-container
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'

    - name: binary-container-prebuild
      runAfter:
        - clone
      taskRef:
        name: binary-container-prebuild-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          subPath: home-dir
          workspace: ws-container
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'

    - name: binary-container-build-x86-64
      runAfter:
        - binary-container-prebuild
      taskRef:
        name: binary-container-build-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          subPath: home-dir
          workspace: ws-container
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-remote-host-auth
          workspace: ws-remote-host-auth
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
        - name: platform
          value: x86_64

    - name: binary-container-build-s390x
      runAfter:
        - binary-container-prebuild
      taskRef:
        name: binary-container-build-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          subPath: home-dir
          workspace: ws-container
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-remote-host-auth
          workspace: ws-remote-host-auth
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
        - name: platform
          value: s390x

    - name: binary-container-build-ppc64le
      runAfter:
        - binary-container-prebuild
      taskRef:
        name: binary-container-build-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          subPath: home-dir
          workspace: ws-container
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-remote-host-auth
          workspace: ws-remote-host-auth
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
        - name: platform
          value: ppc64le

    - name: binary-container-build-aarch64
      runAfter:
        - binary-container-prebuild
      taskRef:
        name: binary-container-build-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          subPath: home-dir
          workspace: ws-container
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-remote-host-auth
          workspace: ws-remote-host-auth
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
        - name: platform
          value: aarch64

    - name: binary-container-postbuild
      runAfter:
        - binary-container-build-x86-64
        - binary-container-build-s390x
        - binary-container-build-ppc64le
        - binary-container-build-aarch64
      taskRef:
        name: binary-container-postbuild-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          subPath: home-dir
          workspace: ws-container
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'

    - name: binary-container-set-results
      runAfter:
        - binary-container-postbuild
      taskRef:
        name: binary-container-set-results-0-1
      workspaces:
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"

  finally:
    - name: binary-container-exit
      taskRef:
        name: binary-container-exit-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          subPath: home-dir
          workspace: ws-container
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
