apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: source-container-0-1  # dot is not allowed in the name
spec:
  params:
    - name: osbs-image
      description: The location of the OSBS builder image (FQDN pullspec)
      type: string
    - name: user-params
      type: string
      description: User parameters in JSON format

  workspaces:
    - name: ws-container
    - name: ws-registries-secret
    - name: ws-koji-secret
    - name: ws-reactor-config-map

  results:
    - name: repositories
      value: $(tasks.source-container-set-results.results.repositories)
    - name: koji-build-id
      value: $(tasks.source-container-set-results.results.koji-build-id)

  tasks:
    - name: source-container-build
      taskRef:
        name: source-container-build-0-1
      workspaces:
      - name: ws-build-dir
        workspace: ws-container
        subPath: build-dir
      - name: ws-context-dir
        workspace: ws-container
        subPath: context-dir
      - name: ws-home-dir
        subPath: home-dir
        workspace: ws-container
      - name: ws-registries-secret
        workspace: ws-registries-secret
      - name: ws-koji-secret
        workspace: ws-koji-secret
      - name: ws-reactor-config-map
        workspace: ws-reactor-config-map
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'

    - name: source-container-set-results
      runAfter:
        - source-container-build
      taskRef:
        name: source-container-set-results-0-1
      workspaces:
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"

  finally:
    - name: source-container-exit
      taskRef:
        name: source-container-exit-0-1
      workspaces:
      - name: ws-build-dir
        workspace: ws-container
        subPath: build-dir
      - name: ws-context-dir
        workspace: ws-container
        subPath: context-dir
      - name: ws-home-dir
        subPath: home-dir
        workspace: ws-container
      - name: ws-registries-secret
        workspace: ws-registries-secret
      - name: ws-koji-secret
        workspace: ws-koji-secret
      - name: ws-reactor-config-map
        workspace: ws-reactor-config-map
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
