apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: source-container-0-1  # dot is not allowed in the name
spec:
  params:
    - name: OSBS_IMAGE
      description: The location of the OSBS builder image (FQDN pullspec)
      type: string
    - name: USER_PARAMS
      type: string
      description: User parameters in JSON format

  workspaces:
    - name: ws-build-dir
    - name: ws-context-dir
    - name: ws-registries-secret
    - name: ws-koji-secret
    - name: ws-reactor-config-map

  results:
    - name: repositories
      value: $(tasks.source-container-set-results.results.repositories)
    - name: koji-build-id
      value: $(tasks.source-container-set-results.results.koji-build-id)

  tasks:
    - name: source-container-build
      taskRef:
        name: source-container-build-0-1
      workspaces:
      - name: ws-build-dir
        workspace: ws-build-dir
      - name: ws-context-dir
        workspace: ws-context-dir
      - name: ws-registries-secret
        workspace: ws-registries-secret
      - name: ws-koji-secret
        workspace: ws-koji-secret
      - name: ws-reactor-config-map
        workspace: ws-reactor-config-map
      params:
        - name: OSBS_IMAGE
          value: "$(params.OSBS_IMAGE)"
        - name: PIPELINE_RUN_NAME
          value: "$(context.pipelineRun.name)"
        - name: USER_PARAMS
          value: "$(params.USER_PARAMS)"

    - name: source-container-set-results
      runAfter:
        - source-container-build
      taskRef:
        name: source-container-set-results-0-1
      workspaces:
        - name: ws-context-dir
          workspace: ws-context-dir
      params:
        - name: OSBS_IMAGE
          value: "$(params.OSBS_IMAGE)"

  finally:
    - name: source-container-exit
      taskRef:
        name: source-container-exit-0-1
      workspaces:
      - name: ws-build-dir
        workspace: ws-build-dir
      - name: ws-context-dir
        workspace: ws-context-dir
      - name: ws-registries-secret
        workspace: ws-registries-secret
      - name: ws-koji-secret
        workspace: ws-koji-secret
      - name: ws-reactor-config-map
        workspace: ws-reactor-config-map
      params:
        - name: OSBS_IMAGE
          value: "$(params.OSBS_IMAGE)"
        - name: PIPELINE_RUN_NAME
          value: "$(context.pipelineRun.name)"
        - name: USER_PARAMS
          value: "$(params.USER_PARAMS)"
