name: Linters

on:
  pull_request:

  push:
    branches:
      - master
      - release_*

jobs:
  bandit:
    name: Bandit analyzer for Python ${{ matrix.os.python }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: fedora
            version: 35
            python: 3
            engine: docker

    steps:
      - uses: actions/checkout@v1

      - run: ./test.sh
        env:
          OS: ${{ matrix.os.name }}
          OS_VERSION: ${{ matrix.os.version }}
          PYTHON_VERSION: ${{ matrix.os.python }}
          ENGINE: ${{ matrix.os.engine }}
          ACTION: bandit
