name: Markdownlint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - release_*

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Run markdownlint
        uses: containerbuildsystem/actions/markdownlint@master
