name: Run tests using test.sh

on: [pull_request]

jobs:
  test:
    name: Python ${{ matrix.os.python }} tests on ${{ matrix.os.name }}-${{ matrix.os.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: centos
            version: 7
            python: 2
            engine: docker

          - name: fedora
            version: 30
            python: 3
            engine: docker

          - name: fedora
            version: 31
            python: 3
            engine: docker

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: test.sh
        env:
          OS: ${{ matrix.os.name }}
          OS_VERSION: ${{ matrix.os.version }}
          PYTHON_VERSION: ${{ matrix.os.python }}
          ENGINE: ${{ matrix.os.engine }}
        run: ./test.sh

      - name: Coveralls Python parallel
        uses: AndreMiras/coveralls-python-action@master
        with:
          parallel: true

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Python finish
        uses: AndreMiras/coveralls-python-action@master
        with:
          parallel-finished: true

  pylint:
    name: Pylint analyzer for Python ${{ matrix.os.python }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - name: fedora
            version: 29
            python: 2
            engine: docker

          - name: fedora
            version: 31
            python: 3
            engine: docker

    steps:
      - uses: actions/checkout@v2

      - run: ./test.sh
        env:
          OS: ${{ matrix.os.name }}
          OS_VERSION: ${{ matrix.os.version }}
          PYTHON_VERSION: ${{ matrix.os.python }}
          ENGINE: ${{ matrix.os.engine }}
          ACTION: pylint

  bandit:
    name: Bandit analyzer for Python ${{ matrix.os.python }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - name: centos
            version: 7
            python: 2
            engine: docker

          - name: fedora
            version: 31
            python: 3
            engine: docker

    steps:
      - uses: actions/checkout@v1

      - run: ./test.sh
        env:
          OS: ${{ matrix.os.name }}
          OS_VERSION: ${{ matrix.os.version }}
          PYTHON_VERSION: ${{ matrix.os.python }}
          ENGINE: ${{ matrix.os.engine }}
          ACTION: bandit
